version: '3.4'
services:
    app:
      image: magnumfaria/build_analisador_credito:latest
      volumes:
        - ../:/opt/build
        - $HOME/.m2:/root/
      command: sh /opt/build/build-install/build.sh